services:
  web:
    image: php:apache
    container_name: php_app
    volumes:
      - ./:/var/www/html/
    ports:
      - 80:80
    depends_on:
      - db
  db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    volumes:
      - db:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE : ${MYSQL_DATABASE}
      MYSQL_USER : ${MYSQL_USER}
      MYSQL_PASSWORD : ${MYSQL_PASSWORD}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: ${PMA_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - db
  
volumes:
  db:

    